steps:
  - label: "echo test"
    command: "echo \"hello world\""

  - label: ':docker: building container'
    key: build
    plugins:
      - "./plugins/docker-compose-buildkite-plugin":
          config: ../docker-compose.yml
          build: app
