steps:
  - label: "echo test"
    command: "echo \"hello world\""

  - label: ':docker: building container'
    key: build
    plugins:
      - docker-compose#v3.7.0:
          config: ../docker-compose.yml
          build: app
